//import dependencies
const { Pool } = require("pg");
const connectionUri = "postgres://postgres:ZTJmMzhlYmFhOWJjZjQ0@0.0.0.0:5432";

//creating connection
const pool = new Pool({
  connectionString: connectionUri,
});

// database connection promise
pool
  .query("SELECT NOW() as now")
  .then((res) => console.log("database connection available."))
  .catch((e) => console.error(e.stack));

// DATABASE SEEDER - THIS PART OF CODE IS USUALLY GENERATED BY ORM LIKE TYPEORM,SEQUELIZE, ETC

//create database if not exists promise
pool
  .query("CREATE DATABASE sorteio")
  .then((res) => console.log("database created."))
  .catch((e) => console.log("database already exists!"));

//creating a pool in the new database
const new_pool = new Pool({
  connectionString: `${connectionUri}/sorteio`,
});

//creating table candidatos in the new DATABASE sorteio
new_pool
  .query(
    "CREATE TABLE IF NOT EXISTS candidates(id SERIAL PRIMARY KEY, first_name VARCHAR(40), last_name VARCHAR(40), email TEXT, created_on TIMESTAMP default current_timestamp)"
  )
  .catch((e) => console.log(e.stack));

// DATABASE SEED END

//export pool query module to be mounted in route main.js
module.exports = {
  query: (text, params) => new_pool.query(text, params),
};
