// DATABASE SEEDER - THIS PART OF CODE IS USUALLY GENERATED BY ORM LIKE TYPEORM,SEQUELIZE, ETC

//import dependencies
const { Pool } = require("pg");
const connectionUri = "postgres://postgres:ZTJmMzhlYmFhOWJjZjQ0@0.0.0.0:5432";

//creating connection
const pool = new Pool({
  connectionString: connectionUri,
});

//promise to create database if not exists
pool
  .query("CREATE DATABASE sorteio")
  .catch((e) => console.log('database already exists'));

//creating a pool in the new database
const sorteio_pool = new Pool({
  connectionString: `${connectionUri}/sorteio`,
});

//creating table candidatos in the new DATABASE sorteio
sorteio_pool
  .query(
    "CREATE TABLE IF NOT EXISTS candidates(id SERIAL PRIMARY KEY, first_name VARCHAR(40), last_name VARCHAR(40), email TEXT, created_on TIMESTAMP default current_timestamp)"
  )
  .catch((e) => console.log(e.stack));

// DATABASE SEED END

module.exports = sorteio_pool;